image: node:alpine

cache:
  paths:
    - node_modules/

stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script: npm install
 
build:
  stage: build
  script: npm run build
  artifacts:
    paths:
      - .next/

test:
  stage: test
  script: npm run test
