image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

stages:
  - setup
  - build
  # - test

setup:
  stage: setup
  script: npm install
 
build:
  stage: build
  script: npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 day

# test:
#   stage: test
#   script: npm run test
