image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script: npm install

build:
  stage: build
  script: npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 day

test-e2e:
  stage: test

  image: mcr.microsoft.com/playwright:v1.22.0-focal
  script:
    - npm run dev --port=3001 & npx wait-on http://localhost:3001
    - npm run test:e2e
  artifacts:
    when: always
    paths:
      - test-reports/
    expire_in: 1 day

test-unit:
  stage: test
  script: echo "unit tests"
