image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

stages:
  - deploy
  - setup
  - build
  - test

setup:
  stage: setup
  script: npm install

build:
  stage: build
  script: npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 day

test-e2e:
  stage: test
  script: echo "e2e tests"
  # image: mcr.microsoft.com/playwright:v1.22.0-focal
  # script:
  #   - npm run dev --port=3001 & npx wait-on http://localhost:3001
  #   - npm run test:e2e
  # artifacts:
  #   when: always
  #   paths:
  #     - test-reports/
  #   expire_in: 1 day

test-unit:
  stage: test
  script: echo "unit tests"

deploy:
  stage: deploy
  dependencies:
    - build
    - test-unit
    - test-e2e

  variables:
    SSH_HOST: "ec2-18-234-128-135.compute-1.amazonaws.com"
    SSH_PATH: "/home/admin/current"
  before_script:
    - 'which ssh-agent || (apk add openssh-client)'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-keyscan ec2-18-234-128-135.compute-1.amazonaws.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - chmod 400 $SSH_KEY
  script:
    - rm -rf node_modules
    - scp -i $SSH_KEY -r . admin@$SSH_HOST:$SSH_PATH