version: "3.9"

services:  
  next:
    build:       
      context: .
      target: next
      ports: 
        - "80:3000"     
      volumes:       
        - ./:/app     
      command: ["npm", "run", "dev"]